# Generated by Django 3.0.6 on 2021-10-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessages',
            name='last_name',
        ),
    ]
